databaseType = "PostgreSql"
name = "Azure Postgre Database"
id = "517e1154-6690-4aff-bce5-380edce8fdd0"

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
schemaModel = "./schema-model"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[flyway]
mixed = true
outOfOrder = true
locations = [ "filesystem:migrations" ]
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[environments.target1]
url = "jdbc:postgresql://database-server-atishay.postgres.database.azure.com:5432/innohack-hackathon"
schemas = [ "public" ]
displayName = "Azure SQL Database"
